<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array("title"=>"آب‌منگل", "city_id"=> 1, "score"=>"3"),
            array("title"=>"آجودانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"احتسابیه", "city_id"=> 1, "score"=>"4"),
            array("title"=>"احتشامیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"اختیاریه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"اراج", "city_id"=> 1, "score"=>"5"),
            array("title"=>"ارغوانیه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"ازگل", "city_id"=> 1, "score"=>"5"),
            array("title"=>"اصفهانک", "city_id"=> 1, "score"=>"2"),
            array("title"=>"افسریه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"اقدسیه ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"الهیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"امامزاده یحیی ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"امانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"امیرآباد ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"امیریه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"اوین", "city_id"=> 1, "score"=>"4"),
            array("title"=>"بازار تهران", "city_id"=> 1, "score"=>"3"),
            array("title"=>"بازارچه مهدی موش", "city_id"=> 1, "score"=>"2"),
            array("title"=>"باغ آذری", "city_id"=> 1, "score"=>"3"),
            array("title"=>"باغ سپه‌سالار", "city_id"=> 1, "score"=>"3"),
            array("title"=>"باغ صبا", "city_id"=> 1, "score"=>"4"),
            array("title"=>"باغ‌فیض", "city_id"=> 1, "score"=>"4"),
            array("title"=>"بریانک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"بلوار نلسون ماندلا ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"بهار ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"بهجت‌آباد ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"پارک شهر", "city_id"=> 1, "score"=>"2"),
            array("title"=>"پارک‌وی", "city_id"=> 1, "score"=>"5"),
            array("title"=>"پامنار", "city_id"=> 1, "score"=>"2"),
            array("title"=>"پل رومی", "city_id"=> 1, "score"=>"5"),
            array("title"=>"پونک", "city_id"=> 1, "score"=>"4"),
            array("title"=>"پیکان‌شهر", "city_id"=> 1, "score"=>"3"),
            array("title"=>"تجریش", "city_id"=> 1, "score"=>"4"),
            array("title"=>"تهران‌پارس", "city_id"=> 1, "score"=>"3"),
            array("title"=>"تهرانسر", "city_id"=> 1, "score"=>"3"),
            array("title"=>"تهران‌نو", "city_id"=> 1, "score"=>"2"),
            array("title"=>"تهران‌ویلا", "city_id"=> 1, "score"=>"3"),
            array("title"=>"تیردوقلو", "city_id"=> 1, "score"=>"1"),
            array("title"=>"جعفرآباد (شمیران)", "city_id"=> 1, "score"=>"3"),
            array("title"=>"جلالیه ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"جماران", "city_id"=> 1, "score"=>"4"),
            array("title"=>"جمشیدیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"جنت‌آباد ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"جوادیه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"جوادیه تهران‌پارس", "city_id"=> 1, "score"=>"1"),
            array("title"=>"جوانمرد قصاب", "city_id"=> 1, "score"=>"2"),
            array("title"=>"خیابان سی‌متری جی", "city_id"=> 1, "score"=>"3"),
            array("title"=>"چاله‌حصار", "city_id"=> 1, "score"=>"2"),
            array("title"=>"چالهرز", "city_id"=> 1, "score"=>"2"),
            array("title"=>"چاله‌میدان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"چهارراه سیدعلی", "city_id"=> 1, "score"=>"2"),
            array("title"=>"چهارصددستگاه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"چیذر", "city_id"=> 1, "score"=>"5"),
            array("title"=>"حسن‌آباد ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"حسن‌آباد و زرگنده", "city_id"=> 1, "score"=>"3"),
            array("title"=>"حصارک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"حکیمیه ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"خاک‌سفید", "city_id"=> 1, "score"=>"1"),
            array("title"=>"خانی‌آباد", "city_id"=> 1, "score"=>"2"),
            array("title"=>"خاوران ", "city_id"=> 1, "score"=>"2"),
            array("title"=>"خوردین", "city_id"=> 1, "score"=>"5"),
            array("title"=>"خیابان پاسداران", "city_id"=> 1, "score"=>"5"),
            array("title"=>"خیابان پیروزی", "city_id"=> 1, "score"=>"3"),
            array("title"=>"خیابان سورنا", "city_id"=> 1, "score"=>"4"),
            array("title"=>"خیابان شهید کلاهدوز", "city_id"=> 1, "score"=>"3"),
            array("title"=>"خیابان قزوین", "city_id"=> 1, "score"=>"3"),
            array("title"=>"خیابان ناصرخسرو", "city_id"=> 1, "score"=>"2"),
            array("title"=>"خیابان هفده شهریور", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دارآباد", "city_id"=> 1, "score"=>"4"),
            array("title"=>"داودیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"دربند ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"درخونگاه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دردشت ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"درکه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دروازه دولاب", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دروازه دولت", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دروازه شمیران", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دروازه غار", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دروازه قزوین", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دروازه محمدیه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دروازه یوسف‌آباد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دروس", "city_id"=> 1, "score"=>"5"),
            array("title"=>"دریان‌نو", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دزاشیب", "city_id"=> 1, "score"=>"5"),
            array("title"=>"دوراهی قپان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"دولت‌آباد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"ده نارمک", "city_id"=> 1, "score"=>"2"),
            array("title"=>"ده ونک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"دهکده المپیک ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"رسالت ", "city_id"=> 1, "score"=>"2"),
            array("title"=>"رستم‌آباد شمیران", "city_id"=> 1, "score"=>"5"),
            array("title"=>"زعفرانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"زیبادشت بالا", "city_id"=> 1, "score"=>"3"),
            array("title"=>"سربند", "city_id"=> 1, "score"=>"4"),
            array("title"=>"سرپولک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"محله سرچشمه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"سعادت‌آباد", "city_id"=> 1, "score"=>"5"),
            array("title"=>"سعدآباد ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"سنگلج", "city_id"=> 1, "score"=>"3"),
            array("title"=>"سوهانک", "city_id"=> 1, "score"=>"5"),
            array("title"=>"سهروردی", "city_id"=> 1, "score"=>"4"),
            array("title"=>"سیدخندان", "city_id"=> 1, "score"=>"4"),
            array("title"=>"سیمون بولیوار", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شاهین شمالی", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شرق تهران", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شمس‌آباد", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شمیران", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شمیران‌نو", "city_id"=> 1, "score"=>"1"),
            array("title"=>"شهر ری", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهر زیبا", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهر نو", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرآرا ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهران", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهرک آپادانا", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک آزمایش ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهرک استقلال", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک اکباتان", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهرک امید", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک دانشگاه تهران", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک ژاندارمری", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهرک سروآزاد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک سلیمانیه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"شهرک غرب", "city_id"=> 1, "score"=>"5"),
            array("title"=>"شهرک قصر فیروزه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"شهرک کارمندان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"شهرک مسعودیه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"شهرک والفجر", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شیان ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"صاحبقرانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"صادقیه", "city_id"=> 1, "score"=>"4"),
            array("title"=>"ضرابخانه", "city_id"=> 1, "score"=>"4"),
            array("title"=>"طرشت", "city_id"=> 1, "score"=>"3"),
            array("title"=>"عباس‌آباد ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"عودلاجان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"فرحزاد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"فرمانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"قاسم‌آباد ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"قلهک", "city_id"=> 1, "score"=>"4"),
            array("title"=>"قنات کوثر", "city_id"=> 1, "score"=>"3"),
            array("title"=>"قیطریه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کاشانک ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کامرانیه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کامرانیه شمالی", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کاووسیه ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کن ", "city_id"=> 1, "score"=>"2"),
            array("title"=>"کن و سولقان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"کوچه خدابنده‌لو", "city_id"=> 1, "score"=>"2"),
            array("title"=>"کوچه لولاگر", "city_id"=> 1, "score"=>"2"),
            array("title"=>"کوی بیمه", "city_id"=> 1, "score"=>"4"),
            array("title"=>"کوی سیزده آبان", "city_id"=> 1, "score"=>"2"),
            array("title"=>"کوی فراز", "city_id"=> 1, "score"=>"5"),
            array("title"=>"کوی فردوس", "city_id"=> 1, "score"=>"3"),
            array("title"=>"گار ماشین", "city_id"=> 1, "score"=>"2"),
            array("title"=>"گلاب‌دره", "city_id"=> 1, "score"=>"3"),
            array("title"=>"گمرک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"گود زنبورک‌خانه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"گورستان ظهیرالدوله", "city_id"=> 1, "score"=>"2"),
            array("title"=>"گیشا ", "city_id"=> 1, "score"=>"4"),
            array("title"=>"لویزان", "city_id"=> 1, "score"=>"3"),
            array("title"=>"مجیدآباد", "city_id"=> 1, "score"=>"2"),
            array("title"=>"مجیدیه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"محله غربت", "city_id"=> 1, "score"=>"2"),
            array("title"=>"محمودیه ", "city_id"=> 1, "score"=>"5"),
            array("title"=>"مسگرآباد", "city_id"=> 1, "score"=>"1"),
            array("title"=>"مشیریه", "city_id"=> 1, "score"=>"2"),
            array("title"=>"منظریه", "city_id"=> 1, "score"=>"5"),
            array("title"=>"منیریه", "city_id"=> 1, "score"=>"3"),
            array("title"=>"مهران", "city_id"=> 1, "score"=>"3"),
            array("title"=>"میدان امام خمینی", "city_id"=> 1, "score"=>"3"),
            array("title"=>"میدان بهارستان", "city_id"=> 1, "score"=>"3"),
            array("title"=>"میدان حسن‌آباد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"میدان خراسان", "city_id"=> 1, "score"=>"3"),
            array("title"=>"مینی‌سیتی", "city_id"=> 1, "score"=>"4"),
            array("title"=>"نارمک", "city_id"=> 1, "score"=>"3"),
            array("title"=>"نازی‌آباد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"نظام‌آباد ", "city_id"=> 1, "score"=>"2"),
            array("title"=>"نواب ", "city_id"=> 1, "score"=>"3"),
            array("title"=>"نیاوران", "city_id"=> 1, "score"=>"5"),
            array("title"=>"نیروی هوایی", "city_id"=> 1, "score"=>"4"),
            array("title"=>"شهرک والفجر ", "city_id"=> 1, "score"=>"2"),
            array("title"=>"وسک", "city_id"=> 1, "score"=>"4"),
            array("title"=>"وصفنارد", "city_id"=> 1, "score"=>"2"),
            array("title"=>"ولنجک", "city_id"=> 1, "score"=>"5"),
            array("title"=>"ونک", "city_id"=> 1, "score"=>"4"),
            array("title"=>"هاشم‌آباد", "city_id"=> 1, "score"=>"2"),
            array("title"=>"هفت حوض", "city_id"=> 1, "score"=>"3"),
            array("title"=>"یاخچی‌آباد", "city_id"=> 1, "score"=>"2"),
            array("title"=>"یافت‌آباد", "city_id"=> 1, "score"=>"3"),
            array("title"=>"یوسف‌آباد", "city_id"=> 1, "score"=>"5")
        );

        foreach ($data as $item) {
            \App\Models\Sector::create($item);
        }
    }
}
