<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $brand = array(
            array('id'=>1, 'title' => 'الیت'),
            array('id'=>2, 'title' => 'آماده لذیذ'),
            array('id'=>3, 'title' => 'هاتی کارا'),
            array('id'=>4, 'title' => 'مهنام'),
            array('id'=>5, 'title' => 'جهان'),
            array('id'=>6, 'title' => 'گلین'),
            array('id'=>7, 'title' => 'دن'),
            array('id'=>8, 'title' => 'ریوا'),
            array('id'=>9, 'title' => 'پاتری'),
            array('id'=>10, 'title' => 'یام یام'),
            array('id'=>11, 'title' => 'چف هو'),
            array('id'=>12, 'title' => 'اندمی'),
            array('id'=>13, 'title' => 'مگی'),
            array('id'=>14, 'title' => 'ترخینه'),
            array('id'=>15, 'title' => 'کنور'),
            array('id'=>16, 'title' => 'سبزان'),
            array('id'=>17, 'title' => 'OAB'),
            array('id'=>18, 'title' => 'گلها'),
            array('id'=>19, 'title' => 'برتر'),
            array('id'=>20, 'title' => 'زر'),
            array('id'=>21, 'title' => 'کوپا'),
            array('id'=>22, 'title' => 'مکسی'),
            array('id'=>23, 'title' => 'بایکیت'),
            array('id'=>24, 'title' => 'کلاب پلاس'),
        );
        $cat = array(
            array('id'=>1,'title'=>'نودل'),
            array('id'=>2,'title'=>'سوپ'),
            array('id'=>3,'title'=>'عصاره'),
            array('id'=>4,'title'=>'ویفر شکلاتی'),
        );
        $sku = array(
            array("title"=>"نودل مرغ الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل گوشت الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل سبزیجات الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل قارچ الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل قارچ و پنیر الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل باربیکیو الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل سس گوجه‌فرنگی تند الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل کاری الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل ماسالا الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"نودل زعفران الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل کودک مرغ الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل کودک سبزیجات الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل کودک گوشت الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل سبوس‌دار مرغ الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل سبوس‌دار گوشت الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل سبوس‌دار سبزیجات الیت", "sku_category_id"=> 1, "brand_id"=> 1, "weight"=>"75"),
            array("title"=>"نودل مرغ آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل گوشت آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل سبزیجات آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل قارچ آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل قارچ و پنیر آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل سس گوجه‌فرنگی تند آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل کاری آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل کودک مرغ آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل کودک گوشت آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل کودک سبزیجات آماده لذیذ", "sku_category_id"=> 1, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"نودل مرغ هاتی کارا", "sku_category_id"=> 1, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"نودل گوشت هاتی کارا", "sku_category_id"=> 1, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"نودل سبزیجات هاتی کارا", "sku_category_id"=> 1, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"نودل کاری هاتی کارا", "sku_category_id"=> 1, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"نودل مرغ و گوجه‌فرنگی هاتی کارا", "sku_category_id"=> 1, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"نودل مرغ مهنام", "sku_category_id"=> 1, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"نودل گوشت مهنام", "sku_category_id"=> 1, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"نودل سبزیجات مهنام", "sku_category_id"=> 1, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"نودل قارچ مهنام", "sku_category_id"=> 1, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"نودل مرغ جهان ", "sku_category_id"=> 1, "brand_id"=> 5, "weight"=>"0"),
            array("title"=>"نودل گوشت جهان", "sku_category_id"=> 1, "brand_id"=> 5, "weight"=>"0"),
            array("title"=>"نودل سبزیجات جهان", "sku_category_id"=> 1, "brand_id"=> 5, "weight"=>"0"),
            array("title"=>"نودل پنیر جهان", "sku_category_id"=> 1, "brand_id"=> 5, "weight"=>"0"),
            array("title"=>"نودل مرغ گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل گوشت گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل سبزیجات گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل مرغ  لیوانی گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل گوشت  لیوانی گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل سبزیجات  لیوانی گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل کاری  لیوانی گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل میگو  لیوانی  گلین", "sku_category_id"=> 1, "brand_id"=> 6, "weight"=>"0"),
            array("title"=>"نودل گوشت دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل مرغ دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل سبزیجات دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل چیلی دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل پاستا پیتزا دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل گوجه و ریحان دن", "sku_category_id"=> 1, "brand_id"=> 7, "weight"=>"0"),
            array("title"=>"نودل گوشت ریوا", "sku_category_id"=> 1, "brand_id"=> 8, "weight"=>"0"),
            array("title"=>"نودل مرغ ریوا", "sku_category_id"=> 1, "brand_id"=> 8, "weight"=>"0"),
            array("title"=>"نودل سبزیجات ریوا", "sku_category_id"=> 1, "brand_id"=> 8, "weight"=>"0"),
            array("title"=>"نودل مرغ پاتری", "sku_category_id"=> 1, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"نودل گوشت پاتری", "sku_category_id"=> 1, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"نودل سبزی پاتری", "sku_category_id"=> 1, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"نودل گوشت یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل مرغ یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل سبزیجات یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل  میگو یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل  کاری یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>" نودل لیوانی گوشت یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل لیوانی مرغ یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل لیوانی سبزیجات یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل لیوانی میگو یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل لیوانی غذای دریایی یام یام", "sku_category_id"=> 1, "brand_id"=> 10, "weight"=>"0"),
            array("title"=>"نودل گوشت چف هو", "sku_category_id"=> 1, "brand_id"=> 11, "weight"=>"0"),
            array("title"=>"نودل مرغ چف هو", "sku_category_id"=> 1, "brand_id"=> 11, "weight"=>"0"),
            array("title"=>"نودل گوشت اندومی", "sku_category_id"=> 1, "brand_id"=> 12, "weight"=>"0"),
            array("title"=>"نودل سبزی اندومی", "sku_category_id"=> 1, "brand_id"=> 12, "weight"=>"0"),
            array("title"=>"نودل رشته سرخ شده اندومی", "sku_category_id"=> 1, "brand_id"=> 12, "weight"=>"0"),
            array("title"=>"نودل مرغ مخصوص اندومی", "sku_category_id"=> 1, "brand_id"=> 12, "weight"=>"0"),
            array("title"=>"نودل مرغ با ادویه بلدی اندومی", "sku_category_id"=> 1, "brand_id"=> 12, "weight"=>"0"),
            array("title"=>"سوپ مرغ اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ سبزي اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ جو و گوجه اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ مرغ و ورميشل اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ مرغ و ذرت اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ جو اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ قارچ اليت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ پیاز فرانسوی الیت", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات و مرغ الیت پلاس", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل و سبزیجات الیت پلاس", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ با خامه الیت پلاس", "sku_category_id"=> 2, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل مگی", "sku_category_id"=> 2, "brand_id"=> 13, "weight"=>"0"),
            array("title"=>"سوپ جو مگی", "sku_category_id"=> 2, "brand_id"=> 13, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ مگی", "sku_category_id"=> 2, "brand_id"=> 13, "weight"=>"0"),
            array("title"=>"سوپ جو و سبزیجات مگی", "sku_category_id"=> 2, "brand_id"=> 13, "weight"=>"0"),
            array("title"=>"سوپ جو و گوجه مگی", "sku_category_id"=> 2, "brand_id"=> 13, "weight"=>"0"),
            array("title"=>"سوپ مرغ مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ جو مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ قارچ مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ مرغ با ورمیشل مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ جو با مرغ و گوجه مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ جو با قارچ مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ ماکارونی با سبزیجات مهنام", "sku_category_id"=> 2, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"سوپ جو هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ زرشک و گوجه فرنگی هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ قارچ هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ مرغ و ورمیشل هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ ماست آذری هاتی کارا", "sku_category_id"=> 2, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"سوپ مرغ ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ سبزی ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ جو ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ قارچ ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ عدس ترخینه", "sku_category_id"=> 2, "brand_id"=> 14, "weight"=>"0"),
            array("title"=>"سوپ جو کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ قارچ کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ مرغ کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ مرغ با چاشنی کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ دوغ کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ عدس کنور", "sku_category_id"=> 2, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"سوپ مرغ سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ جو سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ قارچ سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ جو و گوجه فرنگی سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ تره فرنگی با قارچ سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ اسفناج و قارچ سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ عدس سبزان", "sku_category_id"=> 2, "brand_id"=> 16, "weight"=>"0"),
            array("title"=>"سوپ جو آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ مرغ آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ مرغ و ورميشل آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ قارچ آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ سبزي آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ جو و گوجه آماده لذيذ", "sku_category_id"=> 2, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"سوپ مرغ پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ جو پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ قارچ پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ مرغ با ورمیشل پاتری", "sku_category_id"=> 2, "brand_id"=> 9, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با جوانه ها OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر چهار غله OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با پودر آب پنیر OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با کینوا OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دو سر با فلفل OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با گوجه فرنگی OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با عصاره مرغ OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ جو دوسر با سبزیجات OAB", "sku_category_id"=> 2,"brand_id"=> 17, "weight"=>"0"),
            array("title"=>"سوپ مرغ گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ سبزیجات گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ جو گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ قارچ گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ عدس گلها", "sku_category_id"=> 2, "brand_id"=> 18, "weight"=>"0"),
            array("title"=>"سوپ مرغ برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ سبزی برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ جو برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ قارچ برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ ورمیشل برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ عدس برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ پیاز برتر", "sku_category_id"=> 2, "brand_id"=> 19, "weight"=>"0"),
            array("title"=>"سوپ جو زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"سوپ مرغ زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"سوپ مرغ و ورمیشل زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"سوپ قارچ زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"سوپ جو و قارچ زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"سوپ دال عدس زر", "sku_category_id"=> 2, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره مرغ 8عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره بره 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره گوساله 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره کاري 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره برنج 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره ليمو عماني 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره سير 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره سبزي 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره پياز 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره قارچ 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره جوجه کباب 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره گوجه فرنگی 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره زعفران 8 عددي اليت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره مرغ 12 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره بره 12 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره گوساله 12 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره 48 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"پک عصاره 8 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"پک عصاره 12 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"پک عصاره 48 عددی الیت", "sku_category_id"=> 3, "brand_id"=> 1, "weight"=>"0"),
            array("title"=>"عصاره گوساله 8 عددي آماده لذيذ", "sku_category_id"=> 3, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"عصاره بره 8 عددي آماده لذيذ", "sku_category_id"=> 3, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"عصاره مرغ 8عددي آماده لذيذ", "sku_category_id"=> 3, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"عصاره زعفران 8 عددي آماده لذيذ", "sku_category_id"=> 3, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"پک عصاره 48 عددی آماده لذیذ", "sku_category_id"=> 3, "brand_id"=> 2, "weight"=>"0"),
            array("title"=>"عصاره مرغ مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"عصاره بره مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"عصاره گوساله مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"عصاره سبزیجات مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"عصاره زعفران مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"پک عصاره 48 عددی مهنام", "sku_category_id"=> 3, "brand_id"=> 4, "weight"=>"0"),
            array("title"=>"عصاره ساشه مرغ هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره ساشه گوساله هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره ساشه پیاز هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره ساشه گوجه فرنگی هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره ساشه زعفران هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره 8 عددي مرغ هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره 8 عددي گوساله هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره قوطی مرغ هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره قوطی گوساله هاتی کارا", "sku_category_id"=> 3, "brand_id"=> 3, "weight"=>"0"),
            array("title"=>"عصاره مرغ 12 عددی کنور", "sku_category_id"=> 3, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"عصاره گوساله 12 عددی کنور", "sku_category_id"=> 3, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"عصاره سبزیجات 12 عددی کنور", "sku_category_id"=> 3, "brand_id"=> 15, "weight"=>"0"),
            array("title"=>"عصاره مرغ 2 عددی زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره گوساله 2 عددی زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره سبزیجات 2 عددی زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره 6 عددی گوساله زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره 6 عددی مرغ زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره 6 عددی سبزیجات زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره مرغ 60 عددی زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"عصاره گوساله 60 عددی زر", "sku_category_id"=> 3, "brand_id"=> 20, "weight"=>"0"),
            array("title"=>"ويفر با روکش شکلات شیری کوپا", "sku_category_id"=> 4, "brand_id"=> 21, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات تلخ کوپا", "sku_category_id"=> 4, "brand_id"=> 21, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات فندقی کوپا", "sku_category_id"=> 4, "brand_id"=> 21, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات پرتقالی کوپا", "sku_category_id"=> 4, "brand_id"=> 21, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات شیرنارگیل کوپا", "sku_category_id"=> 4, "brand_id"=> 21, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات تلخ و فندق ماکسی", "sku_category_id"=> 4, "brand_id"=> 22, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات شیری فندقی ماکسی", "sku_category_id"=> 4, "brand_id"=> 22, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات شیری قهوه ماکسی", "sku_category_id"=> 4, "brand_id"=> 22, "weight"=>"0"),
            array("title"=>"ویفر با روکش شکلات شیری نارگیل ماکسی", "sku_category_id"=> 4, "brand_id"=> 22, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی فندقی بایکیت", "sku_category_id"=> 4, "brand_id"=> 23, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی بادام زمینی بایکیت طلایی", "sku_category_id"=> 4, "brand_id"=> 23, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی تلخ  بایکیت", "sku_category_id"=> 4, "brand_id"=> 23, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی بارسلونا کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی یونتوس کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی لیورپول کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی رئال مادرید کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی بایرن مونیخ کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0"),
            array("title"=>"ویفر شکلاتی منچستر کلاب پلاس ", "sku_category_id"=> 4, "brand_id"=> 24, "weight"=>"0")
        );
        foreach ($brand as $item) {
            \App\Models\Brand::create($item);
        } foreach ($cat as $item) {
            \App\Models\SkuCategory::create($item);
        } foreach ($sku as $item) {
            \App\Models\Sku::create($item);
        }
    }
}
